// Panel 4 — Executive Outputs
// 3 tabs: Standup Summary, Escalation Memo, Risk Digest
// Matches atis_dashboard_v3.html Panel 4 exactly

import { useState } from 'react'

const SEV_COLOR = {
  CRITICAL: '#dc2626',
  HIGH:     '#ea580c',
  MEDIUM:   '#d97706',
  LOW:      '#78716c',
}

const S = {
  heading: {
    fontSize: '22px', fontWeight: 700, fontStyle: 'italic',
    color: '#0f172a', marginBottom: '6px', fontFamily: 'Georgia, serif',
  },
  sub: {
    fontSize: '13px', color: '#44403c',
    fontFamily: 'system-ui, sans-serif', marginBottom: '24px',
  },
  tabs: {
    display: 'flex', borderBottom: '1.5px solid #0f172a', marginBottom: '24px',
  },
  tab: (active) => ({
    fontSize: '11px', fontWeight: 700, letterSpacing: '0.08em',
    textTransform: 'uppercase', padding: '8px 20px',
    cursor: 'pointer', color: active ? '#0f172a' : '#44403c',
    background: 'none', border: 'none',
    borderBottom: active ? '2px solid #0f172a' : '2px solid transparent',
    marginBottom: '-1.5px', fontFamily: 'system-ui, sans-serif',
    transition: 'color 0.12s',
  }),
  docCard: {
    background: '#ffffff', border: '0.5px solid #d6d3d1',
    borderRadius: '8px', padding: '28px 32px', maxWidth: '720px',
  },
  docMeta: {
    display: 'flex', gap: '16px', fontSize: '10px', color: '#44403c',
    letterSpacing: '0.06em', textTransform: 'uppercase',
    fontFamily: 'system-ui, sans-serif',
    marginBottom: '20px', paddingBottom: '16px',
    borderBottom: '0.5px solid #e7e5e4',
  },
  docBody: {
    fontSize: '14px', color: '#1c1917',
    lineHeight: 1.9, fontFamily: 'Georgia, serif',
  },
  noContent: {
    fontSize: '13px', color: '#78716c',
    fontFamily: 'system-ui, sans-serif', fontStyle: 'italic',
    textAlign: 'center', padding: '40px 0',
  },
  digestRow: {
    display: 'flex', alignItems: 'baseline', gap: '16px',
    padding: '12px 0', borderBottom: '0.5px solid #e7e5e4',
    fontFamily: 'system-ui, sans-serif',
  },
  digestSev: {
    fontSize: '10px', fontWeight: 700, letterSpacing: '0.07em',
    textTransform: 'uppercase', width: '64px', flexShrink: 0,
  },
  digestId: {
    fontStyle: 'italic', fontFamily: 'Georgia, serif',
    color: '#44403c', fontSize: '12px', width: '72px', flexShrink: 0,
  },
  digestDesc: { fontSize: '13px', color: '#1c1917', flex: 1 },
}

function formatDate(isoStr) {
  if (!isoStr) return ''
  try {
    return new Date(isoStr).toLocaleString('en-US', {
      month: 'short', day: 'numeric',
      hour: '2-digit', minute: '2-digit', hour12: false,
    })
  } catch { return '' }
}

// Parse risk digest text into rows
function parseDigest(content) {
  if (!content) return []
  return content.split('\n').filter(l => l.trim()).map(line => {
    // Format: "Program · TICKET-ID · FLAG [SEVERITY] — description"
    const match = line.match(/·\s*([\w-]+)\s*·\s*(\w+)\s*\[(\w+)\]\s*[—–-]\s*(.+)/)
    if (match) {
      return { id: match[1], flag: match[2], severity: match[3], desc: match[4].trim() }
    }
    // Fallback: show raw line
    return { id: null, flag: null, severity: null, desc: line }
  })
}

// Render standup / escalation memo as paragraphs
function DocBody({ content }) {
  if (!content) return null
  const paragraphs = content.split(/\n\n+/).filter(p => p.trim())
  return (
    <div style={S.docBody}>
      {paragraphs.map((p, i) => (
        <p key={i} style={{ marginBottom: i < paragraphs.length - 1 ? '14px' : 0 }}>
          {p.trim()}
        </p>
      ))}
    </div>
  )
}

export default function ExecutiveOutputs({ outputs, lastCycle, program }) {
  const [activeTab, setActiveTab] = useState('standup')
  const programName = program?.name || 'Project Atlas'

  const standup = outputs?.standup_summary
  const escalation = outputs?.escalation_memo
  const digest = outputs?.risk_digest

  const digestRows = parseDigest(digest?.content)

  return (
    <div>
      <div style={S.heading}>Executive Outputs</div>
      <div style={S.sub}>Documents generated by the Communication Agent this cycle. Ready to send.</div>

      <div style={S.tabs}>
        {[
          { id: 'standup',    label: 'Standup Summary' },
          { id: 'escalation', label: 'Escalation Memo' },
          { id: 'digest',     label: 'Risk Digest'     },
        ].map(({ id, label }) => (
          <button
            key={id}
            style={S.tab(activeTab === id)}
            onClick={() => setActiveTab(id)}
            onMouseEnter={e => { if (activeTab !== id) e.currentTarget.style.color = '#0f172a' }}
            onMouseLeave={e => { if (activeTab !== id) e.currentTarget.style.color = '#44403c' }}
          >
            {label}
          </button>
        ))}
      </div>

      {/* Standup Summary */}
      {activeTab === 'standup' && (
        standup ? (
          <div style={S.docCard}>
            <div style={S.docMeta}>
              <span>Cycle #{standup.cycle_number}</span>
              <span>Generated {formatDate(standup.created_at)}</span>
              <span>{programName}</span>
            </div>
            <DocBody content={standup.content} />
          </div>
        ) : (
          <div style={S.docCard}>
            <div style={S.noContent}>Waiting for the first cycle to complete…</div>
          </div>
        )
      )}

      {/* Escalation Memo */}
      {activeTab === 'escalation' && (
        <div style={S.docCard}>
          {escalation ? (
            <>
              <div style={S.docMeta}>
                <span>Escalation Memo</span>
                <span>To: Program Lead</span>
                <span>Cycle #{escalation.cycle_number} · {formatDate(escalation.created_at)}</span>
              </div>
              <DocBody content={escalation.content} />
            </>
          ) : (
            <>
              <div style={S.docMeta}>
                <span>Escalation Memo</span>
                <span>{programName}</span>
              </div>
              <div style={S.noContent}>No escalation required this cycle.</div>
            </>
          )}
        </div>
      )}

      {/* Risk Digest */}
      {activeTab === 'digest' && (
        digest ? (
          <div style={S.docCard}>
            <div style={S.docMeta}>
              <span>{digestRows.length} active risk{digestRows.length !== 1 ? 's' : ''}</span>
              <span>Cycle #{digest.cycle_number} · {formatDate(digest.created_at)}</span>
            </div>
            {digestRows.map((row, i) => (
              <div
                key={i}
                style={{
                  ...S.digestRow,
                  borderBottom: i < digestRows.length - 1 ? '0.5px solid #e7e5e4' : 'none',
                }}
              >
                {row.severity ? (
                  <>
                    <span style={{ ...S.digestSev, color: SEV_COLOR[row.severity] || '#44403c' }}>
                      {row.severity.charAt(0) + row.severity.slice(1).toLowerCase()}
                    </span>
                    <span style={S.digestId}>{row.id}</span>
                    <span style={S.digestDesc}>{row.desc}</span>
                  </>
                ) : (
                  <span style={S.digestDesc}>{row.desc}</span>
                )}
              </div>
            ))}
          </div>
        ) : (
          <div style={S.docCard}>
            <div style={S.noContent}>No risk digest available yet.</div>
          </div>
        )
      )}
    </div>
  )
}
