"""add_escalations_table

Revision ID: 3a525f75665e
Revises: fe1385257e8a
Create Date: 2026-05-20 15:19:46.577952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a525f75665e'
down_revision: Union[str, None] = 'fe1385257e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('ticket_id', sa.String(length=100), nullable=False),
    sa.Column('flag', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('suggested_owner', sa.String(length=255), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_escalations_program_created', 'escalations', ['program_id', 'created_at'], unique=False)
    op.create_index('ix_escalations_program_run', 'escalations', ['program_id', 'run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_escalations_program_run', table_name='escalations')
    op.drop_index('ix_escalations_program_created', table_name='escalations')
    op.drop_table('escalations')
    # ### end Alembic commands ###
