"""initial_schema

Revision ID: fe1385257e8a
Revises: 
Create Date: 2026-05-19 15:08:51.635381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe1385257e8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('context_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_decisions_program_created', 'agent_decisions', ['program_id', 'created_at'], unique=False)
    op.create_index('ix_agent_decisions_program_run', 'agent_decisions', ['program_id', 'run_id'], unique=False)
    op.create_table('executive_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('output_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executive_outputs_program_type_created', 'executive_outputs', ['program_id', 'output_type', 'created_at'], unique=False)
    op.create_table('operational_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'key', name='uq_operational_memory_program_key')
    )
    op.create_index('ix_operational_memory_program_key', 'operational_memory', ['program_id', 'key'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_badge', sa.String(length=10), nullable=True),
    sa.Column('worst_severity', sa.String(length=10), nullable=True),
    sa.Column('last_run_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=5), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('sprint_id', sa.String(length=100), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('points_completed', sa.Integer(), nullable=True),
    sa.Column('is_on_critical_path', sa.Boolean(), nullable=True),
    sa.Column('blocker_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stale_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope_changed', sa.Boolean(), nullable=True),
    sa.Column('milestone_target', sa.String(length=255), nullable=True),
    sa.Column('risk_flag', sa.String(length=20), nullable=True),
    sa.Column('risk_severity', sa.String(length=10), nullable=True),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tickets_assignee_status', 'tickets', ['assignee', 'status'], unique=False)
    op.create_index('ix_tickets_program_sprint', 'tickets', ['program_id', 'sprint_id'], unique=False)
    op.create_index('ix_tickets_program_status', 'tickets', ['program_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_program_status', table_name='tickets')
    op.drop_index('ix_tickets_program_sprint', table_name='tickets')
    op.drop_index('ix_tickets_assignee_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('sprints')
    op.drop_index('ix_operational_memory_program_key', table_name='operational_memory')
    op.drop_table('operational_memory')
    op.drop_index('ix_executive_outputs_program_type_created', table_name='executive_outputs')
    op.drop_table('executive_outputs')
    op.drop_index('ix_agent_decisions_program_run', table_name='agent_decisions')
    op.drop_index('ix_agent_decisions_program_created', table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_table('programs')
    # ### end Alembic commands ###
